name: smartroute
description: 생활 일정 네비게이션 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.10
  
  # Utils
  uuid: ^4.2.2
  intl: ^0.20.2
  logger: ^2.0.2
  shared_preferences: ^2.2.2
  
  # Network
  http: ^1.1.2
  
  # Map
  webview_flutter: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/logo.png
